### PR TITLE
 ⬆️Update deprecated import of expo

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by wcandillon** [comment]
Just tested while upgrading to expo31 and that fixes the deprecation warnings.

**Review by gre — APPROVED** [review]
thanks a lot William

**Comment by wcandillon** [comment]
My pleasure 🙌🏻 let me know when it's published upstream in gl-react-expo (not urgent)

**Comment by gre** [comment]
I'm adding myself an issue to not forget releasing it. hopefully this weekend

**Pull request merged**
